cmake_minimum_required(VERSION 3.19)
project(Corbomite_BasesTests LANGUAGES CXX)
enable_testing()
find_package(Qt6 REQUIRED COMPONENTS Test)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)

add_executable(tst_bases_value_null tst_value_null.cpp)
add_test(NAME tst_bases_value_null COMMAND tst_bases_value_null)
target_link_libraries(tst_bases_value_null PRIVATE Qt6::Test Corbomite::Bases)

add_executable(tst_bases_value_primitive tst_value_primitive.cpp)
add_test(NAME tst_bases_value_primitive COMMAND tst_bases_value_primitive)
target_link_libraries(tst_bases_value_primitive PRIVATE Qt6::Test Corbomite::Bases)
