cmake_minimum_required(VERSION 3.19)
project(markoff_tests LANGUAGES CXX)
enable_testing()
find_package(Qt6 REQUIRED COMPONENTS Test)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)

add_executable(tst_markoff_document tst_document.cpp)
add_test(NAME tst_markoff_document COMMAND tst_markoff_document)
target_link_libraries(tst_markoff_document PRIVATE Qt6::Test markoff)
set_tests_properties(tst_markoff_document PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")

add_executable(tst_markoff_renderer tst_renderer.cpp)
add_test(NAME tst_markoff_renderer COMMAND tst_markoff_renderer)
target_link_libraries(tst_markoff_renderer PRIVATE Qt6::Test markoff)
set_tests_properties(tst_markoff_renderer PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
